pipeline:
  test:
    image: maven:alpine
    environment:
      - DOCKER_API_VERSION=1.32
      - DOCKER_HOST=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
     - mvn clean test
     - mvn clean install
